version: '3'
services:
  mongo:
    container_name: MongoDbServer
    image: mongo:latest
    env_file: ".env"
    environment:
      - AUTH=yes
      - MONGO_INITDB_ROOT_USERNAME=<username>
      - MONGO_INITDB_ROOT_PASSWORD=<password>
    volumes:
      - ${MONGODB_HOST_DATA}/db:/data/db
    ports:
      - "27017:27017"
