FROM node:lts-slim

ARG PORT=5000

RUN mkdir -p /opt/app

WORKDIR /opt/app

RUN npm install -g pnpm

COPY ../package.json ../pnpm-lock.yaml  ./

RUN pnpm install --frozen-lockfile

COPY ../src/ ./src/

COPY ../startup.js ./
COPY ../.env ./

EXPOSE $PORT

CMD [ "pnpm", "start:docker"]
